exports.mapping = {
  "indices/sti": {
    type: "cfd",
    ticker: "TVC:STI",
    name: "STI (SG)",
    region: "ASIA",
    symbol: "STI",
  },
  "currencies/us-dollar-index": {
    type: "cfd",
    ticker: "TVC:DXY",
    name: "USD Index (DXY)",
  },
  "bonds/us-10y": {
    type: "cfd",
    ticker: "TVC:US10Y",
    name: "US10Yr",
  },
  "stocks/tlk-us": {
    type: "america",
    ticker: "NYSE:TLK",
    name: "TLKM (US)",
  },
  "etf/eido": {
    type: "america",
    ticker: "AMEX:EIDO",
    name: "EIDO",
  },
  "mf/eem": {
    type: "america",
    ticker: "AMEX:EEM",
    name: "EEM",
  },
  "commodities/indonesian-coal": {
    ticker: "NYMEX:ICI",
    name: "Indonesian Coal",
    month: 0,
    symbol: "Indonesian\nCoal\n",
  },
  "commodities/newcastle-coal-1": {
    ticker: "ICEEUR:NCF",
    name: "Newcastle Coal",
    month: 0,
    symbol: "Newcastle\nCoal\n",
  },
  "commodities/newcastle-coal-2": {
    ticker: "ICEEUR:NCF",
    name: "Newcastle Coal",
    month: 1,
    symbol: "Newcastle\nCoal\n",
  },
  "commodities/rotterdam-coal-1": {
    ticker: "ICEEUR:ATW",
    name: "Rotterdam Coal",
    month: 0,
    symbol: "Rotterdam\nCoal\n",
  },
  "commodities/rotterdam-coal-2": {
    ticker: "ICEEUR:ATW",
    name: "Rotterdam Coal",
    month: 1,
    symbol: "Rotterdam\nCoal\n",
  },
  "commodities/malaysia-cpo": {
    ticker: "MYX:FCPO",
    name: "CPO Malaysia",
    month: 2,
    symbol: "CPO\n",
  },
  "commodities/copper": {
    type: "america",
    ticker: "COMEX:HG1!",
    name: "Copper",
  },
  "commodities/crude-oil": {
    ticker: "USOIL",
    name: "Crude Oil WTI",
    symbol: "WTI\nOil",
  },
  "commodities/brent-oil": {
    ticker: "TVC:UKOIL",
    name: "Brent Oil",
    symbol: "Brent\nOil",
  },
  "indices/us-30": {
    type: "america",
    ticker: "DJ:DJI",
    region: "US",
    symbol: "DJI",
    name: "DJIA",
  },
  "indices-futures/us-30": {
    ticker: "CBOT_MINI:YM",
    month: 2,
    name: "DJI Futures",
    region: "US",
    symbol: "DJI Futures",
  },
  "indices/us-spx-500": {
    type: "america",
    ticker: "SP:SPX",
    region: "US",
    symbol: "S&P 500",
    name: "S&P 500",
  },
  "indices/nq-100-ixic": {
    type: "cfd",
    ticker: "TVC:IXIC",
    region: "US",
    name: "NASDAQ",
    symbol: "NASDAQ",
  },
  "indices/germany-30": {
    ticker: "XETR:DAX",
    region: "EU",
    symbol: "DAX (Germany)",
    name: "DAX (Germany)",
  },
  "indices/uk-100": {
    type: "cfd",
    ticker: "TVC:UKX",
    region: "EU",
    name: "FTSE (UK)",
    symbol: "FTSE (UK)",
  },
  "indices/france-40": {
    ticker: "EURONEXT:PX1",
    region: "EU",
    symbol: "CAC (France)",
    name: "CAC (France)",
  },
  "indices/japan-ni225": {
    ticker: "TVC:NI225",
    region: "ASIA",
    symbol: "NIKKEI",
    name: "NIKKEI (JP)",
  },
  "indices/hongkong-hk50": {
    ticker: "HSI:HSI",
    region: "ASIA",
    symbol: "HSI",
    name: "Hang Seng (HK)",
  },
  "indices/shanghai-sec": {
    ticker: "SSE:000001",
    region: "ASIA",
    symbol: "SHANGHAI",
    name: "SHANGHAI (CN)",
  },
  "indices/shenzen-sec": {
    ticker: "SZSE:399001",
    region: "ASIA",
    symbol: "SHENZEN",
    name: "SHENZEN (CN)",
  },
  "indices/korea-ks11": {
    ticker: "TVC:KOSPI",
    region: "ASIA",
    symbol: "KOSPI",
    name: "KOSPI (KR)",
  },
  "indices/malaysia-fbmklci": {
    ticker: "FTSEMYX:FBMKLCI",
    region: "ASIA",
    symbol: "FBMKLCI",
    name: "FBMKLCI (MY)",
  },
  "indices/india-nifty50": {
    ticker: "NSE:NIFTY",
    region: "ASIA",
    symbol: "NIFTY",
    name: "NIFTY (IN)",
  },
  "indices/indonesia-jkse": {
    ticker: "IDX:COMPOSITE",
    region: "ASIA",
    symbol: "IHSG",
    name: "IHSG",
  },
  "indices/indonesia-lq45": {
    ticker: "IDX:LQ45",
    region: "ASIA",
    symbol: "LQ45",
    name: "LQ45",
  },
};
